### ISSUE TITLE
Part Four(B): Split the app into microservices

### ISSUE THREAD

**Issue by pacyL2K19** [pacyL2K19/graphql-mongodb-nestjs-tutorial#6]
# Part 4(B): From monolith to microservices

## TODO 🛠️ 

- [x] Create the microservice architecture, using the event pattern and resource-sharing pattern
- [x] Create events that make ms communicate together
- [ ] Improve CI/CD pipelines
